services:
  app:
    build: .
    expose:
      - "8080"
    env_file: .env
    volumes:
      - ./app:/app
      - ./pdfs:/pdfs
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
  nginx:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./pdfs:/usr/share/nginx/html/pdfs
      - ./client:/usr/share/nginx/html/client
    depends_on:
      - app
    restart: unless-stopped
